version: '3.9'
services:
  db:
    image: mongo
    container_name: poetry-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - esnet
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_URL=mongodb://admin:secret@db:27017/
    depends_on:
      - db
    networks:
      - esnet
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: poetry-worker
    restart: always
    ports:
      - "8082:8082"
    environment:
      - WORKER_PORT=8082
      - WORKER_BUFFER_SIZE=20
      - WORKER_MAX_WORKERS=5
      - DB_HOST=db
      - DB_PORT=27017
      - DB_USER=admin
      - DB_PASS=secret
      - DB_NAME=poetry
    depends_on:
      - db
    networks:
      - esnet
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: poetry-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - WORKER_HOST=worker
      - WORKER_PORT=8082
      - DB_HOST=db
      - DB_PORT=27017
      - DB_USER=admin
      - DB_PASS=secret
      - DB_NAME=poetry
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - db
      - elasticsearch
      - worker
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.4
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
